### ISSUE TITLE
Clarify in installation instructions how much shared memory is needed (MacOS)

### ISSUE THREAD

**Issue by ivalaginja** [spacetelescope/catkit2#73]
The installation instructions in the readme of catkit2 just state that the default of 4 MB of shared memory on MacOS is not enough, but not how much is recommended (see https://github.com/spacetelescope/catkit2#shared-memory-configuration).

It seems like no action is needed for MacOS Catalina. I am on MacOS Monterey however, and from what I can tell its default is still at around 4 MB. I found this set of instructions how to deal with shared memory allocation on MacOS:
http://www.spy-hill.net/help/apple/SharedMemory.html
Edit: I also found this link useful: https://www.postgresql.org/docs/8.4/kernel-resources.html

And when I run `sysctl -A | grep shm` on my MacOS 12.2 (Monterey) it returns:
```bash
kern.sysv.shmall: 1024
kern.sysv.shmmax: 4194304
kern.sysv.shmmin: 1
kern.sysv.shmmni: 32
kern.sysv.shmseg: 8
```

The current value for `kern.sysv.shmmax` suggests a max of ~4MB if I see that right, is that correct?

The link above tells me how to change my shared memory settings but I don't know at this point what the recommended settings are.

@ehpor what would you suggest I try? If whatever I try works fine, I can update the readme accordingly.

**Comment by RemiSoummer** [comment]
@ivalaginja @ehpor , I'm reviving this discussion with @raphaelpclt.  
I'm running Ventura 13.6 and been working on re-installing everything from scratch (as well as working on updating install documentation).   Trying to run the GUI in simulation I have a `AttributeError: Too many open files`
which seems related to the discussion about sysctl above.  I'm investigating how to increase that, and will put that in my PR documentation when we find the solution.

**Comment by ivalaginja** [comment]
@RemiSoummer you should pull @alexisyslau into the loop, she's been having exactly the same issue on her machine and has found a solution for it.

**Comment by RemiSoummer** [comment]
Thanks and yes I'm interested we are going in circles for now.

**Comment by RemiSoummer** [comment]
I just upgraded to Sonoma 14.4 and the problem is gone :-)  
Still interested in getting the solution documented since that might likely come back. 

For completeness this is what I have now: 

`$ sysctl -A | grep maxfiles`
```
kern.maxfiles: 245760
kern.maxfilesperproc: 122880
```
and also: 

`$ sysctl -A | grep shm`
```
kern.sysv.shmmax: 4194304
kern.sysv.shmmin: 1
kern.sysv.shmmni: 32
kern.sysv.shmseg: 8
kern.sysv.shmall: 1024
machdep.pmap.hashmax: 11
security.mac.posixshm_enforce: 1
security.mac.sysvshm_enforce: 1
```

**Comment by alexisyslau** [comment]
After testing with Iva's DataStream test, I think the problem is not with `kern.maxfiles` but with` ulimit -n` Perhaps some of you would have a better understanding of these settings. 

From the tests I have conducted, ulimit -n limits how many files can be opened at once by the shell.

If you change `ulimit -n` to something higher (e.g., 1,000,000), you should be able to open 1,000,000 DataStreams without any issue. Currently, I do not know the upper limit for Mac.

A temporary (or semi-permanent) solution is to add: `echo 'ulimit -n 1000000' `to your shell profile (e.g., bash). Then ulimit -n would be changed each time you access the shell.

Sanity check to make sure the number of file descriptor has been changed would be: ulimit -n or ulimit -a (show other parameters and also their descriptions).

**Comment by ivalaginja** [comment]
For the record, the test, which should probably be committed to the repo:

```python
from catkit2.catkit_bindings import DataStream
from tqdm import tqdm


streams = []

for i in tqdm(range(100000)):
    service_id = f'tessdft{i}'

    stream = DataStream.create('tester', service_id, 'int8', [1], 20)
    streams.append(stream)

    stream2 = DataStream.open(stream.stream_id)
    streams.append(stream2)
```

**Comment by ehpor** [comment]
@ivalaginja Agreed. Just a small detail: both the shared memory of the created and the opened `DataStream` count as an open file to the operating system. Depending on the operating system, the synchronization part of a `DataStream` can count as a few open files as well, but I'm not quite sure about the details there. (Semaphores may count as a file. They are at least open handles.)

**Comment by alexisyslau** [comment]
the following changes work on my setup: 
Create `/etc/sysctl.conf`

Within `/etc/sysctl.conf`, 

```
kern.sysv.shmmax: 1073741824
kern.sysv.shmmin: 1
kern.sysv.shmmni: 128
kern.sysv.shmseg: 512
kern.sysv.shmall: 1073741824
kern.maxfiles: 491520
kern.maxfilesperproc: 245760
security.mac.posixshm_enforce: 1
security.mac.sysvshm_enforce: 1
```

**Comment by alexisyslau** [comment]
to test, check this link: [https://github.com/facebook/watchman/issues/880](url)

**Comment by alexisyslau** [comment]
btw I am on Sonoma 14.6, and the problem was solved after adding the configuration file. You might need to restart the computer or load the config file.

**Comment by RemiSoummer** [comment]
my laptop, 15.3.1, running into the issue after fresh re-install and crashing in the simulator. 

> Too many open files (src/kqueue.cpp:35)
> Fatal Python error: Aborted
> 
> Current thread 0x0000000202b49200 (most recent call first):
>   File "/Users/soummer/git_repos/catkit2/catkit2/testbed/service_proxy.py", line 22 in __init__
>   File "/Users/soummer/git_repos/hicat-package2/hicat2/service_proxies/hicat_camera_proxy.py", line 10 in __init__
>   File "/Users/soummer/git_repos/catkit2/catkit2/testbed/testbed_proxy.py", line 38 in get_service
>   File "hicat_simulator.py", line 89 in camera_readout
>   File "/Users/soummer/git_repos/catkit2/catkit2/simulator/simulator.py", line 304 in callback
>   File "/Users/soummer/git_repos/catkit2/catkit2/simulator/simulator.py", line 133 in main
>   File "hicat_simulator.py", line 319 in <module>
> Abort trap: 6
>

**Comment by RemiSoummer** [comment]
New loaner laptop with fresh OS, 15.3.1 Sequoia, fresh install from total scratch.   Same error (though hitting somewhere else). 
Tried updating the shmmax parameter in sysctl.conf (checked it's updated after reboot).  However, the error persists, so it seems it's not taken into account anymore.

**Comment by RemiSoummer** [comment]
In the end the issue `Too many open files` is not related to the shmmax value. 
This is solved by increasing `ulimit`.   this is addressed in #294

**Comment by RemiSoummer** [comment]
Since all this has been _very_ dependent on the OS version, the shared memory issue might re-surface at some point and we are seeing this issue open for now.
